name: Lint

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - '**.md'

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
#          - windows-latest
    name: Golangci-Lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          args: -E gofumpt -E gocritic -E misspell -E revive -E godot
